.TH "KinovaArm" 3 "Wed Jun 24 2020" "Collision monitoring for robotic manipulators" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KinovaArm \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kinova_arm\&.h>\fP
.PP
Inherits \fBArm\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKinovaArm\fP (std::string urdf_filename)"
.br
.ti -1c
.RI "\fBKinovaArm\fP (std::string urdf_filename, Eigen::Matrix4d inputBaseTransform)"
.br
.ti -1c
.RI "\fB~KinovaArm\fP ()"
.br
.RI "\fI\fBKinovaArm\fP Destructor\&. \fP"
.ti -1c
.RI "bool \fBupdatePose\fP (std::vector< double > jointPositions)"
.br
.ti -1c
.RI "std::vector< double > \fBikVelocitySolver\fP (KDL::Twist twist)"
.br
.ti -1c
.RI "Eigen::Matrix4d \fBgetPose\fP (void)"
.br
.ti -1c
.RI "Eigen::Matrix4d \fBgetPose\fP (int jointNumber)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "KDL::JntArray \fBjointArray\fP"
.br
.RI "\fIThe KDL joint array to hold the joint angles\&. \fP"
.ti -1c
.RI "KDL::JntArray \fBjointVels\fP"
.br
.RI "\fIThe KDL joint array to hold the joint velocities\&. \fP"
.ti -1c
.RI "int \fBnFrames\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An implementation of the \fBArm\fP interface\&.
.PP
This implementation is specifically for the KINOVA arm in the HBRS robotics lab\&. 
.PP
Definition at line 35 of file kinova_arm\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KinovaArm::KinovaArm (std::string urdf_filename)"
\fBKinovaArm\fP constructor
.PP
\fBParameters:\fP
.RS 4
\fIurdf_filename\fP The global location of the urdf file used to import the arm kinematics model 
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of \fBKinovaArm\fP class 
.RE
.PP
This is used to import the URDF file 
.PP
Definition at line 7 of file kinova_arm\&.cpp\&.
.SS "KinovaArm::KinovaArm (std::string urdf_filename, Eigen::Matrix4d inputBaseTransform)"
\fBKinovaArm\fP constructor with set baseposition
.PP
\fBParameters:\fP
.RS 4
\fIurdf_filename\fP The global location of the urdf file used to import the arm kinematics model 
.br
\fIinputBaseTransform\fP The global position of the robot base 
.RE
.PP
\fBReturns:\fP
.RS 4
An instance of \fBKinovaArm\fP class 
.RE
.PP
This is used to import the URDF file 
.PP
Definition at line 85 of file kinova_arm\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "Eigen::Matrix4d KinovaArm::getPose (void)\fC [virtual]\fP"
A function to find the final joint pose
.PP
\fBReturns:\fP
.RS 4
The last joint pose 
.RE
.PP

.PP
Implements \fBArm\fP\&.
.PP
Definition at line 256 of file kinova_arm\&.cpp\&.
.SS "Eigen::Matrix4d KinovaArm::getPose (int jointNumber)\fC [virtual]\fP"
A function to find the joint pose of a given joint
.PP
\fBParameters:\fP
.RS 4
\fIjointNumber\fP The joint number to solve for the pose of 
.RE
.PP
\fBReturns:\fP
.RS 4
The last joint pose 
.RE
.PP

.PP
Implements \fBArm\fP\&.
.PP
Definition at line 261 of file kinova_arm\&.cpp\&.
.SS "std::vector< double > KinovaArm::ikVelocitySolver (KDL::Twist twist)"
A function to find the inverse kinematics of an endeffector trajectory
.PP
\fBParameters:\fP
.RS 4
\fItwist\fP The KDL::Twist velocity vector 
.RE
.PP
\fBReturns:\fP
.RS 4
A vector of joint velocities used to achieve the desired velocity 
.RE
.PP

.PP
Definition at line 210 of file kinova_arm\&.cpp\&.
.SS "bool KinovaArm::updatePose (std::vector< double > jointPositions)\fC [virtual]\fP"
A function to update the current virtual representation of the arm
.PP
\fBParameters:\fP
.RS 4
\fIjointPositions\fP The angular positions of the arm joints in order of the joint in radians 
.RE
.PP
\fBReturns:\fP
.RS 4
The boolean true for a successful update, False otherwise 
.RE
.PP

.PP
Reimplemented from \fBArm\fP\&.
.PP
Definition at line 167 of file kinova_arm\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Collision monitoring for robotic manipulators from the source code\&.
