.TH "KinovaSimulator" 3 "Wed Jun 24 2020" "Collision monitoring for robotic manipulators" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KinovaSimulator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsubVelocity\fP (const sensor_msgs::JointState::ConstPtr &msg)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBinputTopic\fP"
.br
.ti -1c
.RI "std::string \fBoutputTopic\fP"
.br
.ti -1c
.RI "ros::Subscriber \fBsubscriber\fP"
.br
.ti -1c
.RI "ros::Publisher \fBvelPub\fP"
.br
.ti -1c
.RI "uint64_t \fBcurTime\fP"
.br
.ti -1c
.RI "uint64_t \fBprevTime\fP"
.br
.ti -1c
.RI "uint64_t \fBdeltaT\fP"
.br
.ti -1c
.RI "std::vector< double > \fBjointVelocities\fP"
.br
.ti -1c
.RI "std::vector< double > \fBjointPositions\fP"
.br
.ti -1c
.RI "sensor_msgs::JointState \fBjointStates\fP"
.br
.ti -1c
.RI "ros::Time \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file robot_sim\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Collision monitoring for robotic manipulators from the source code\&.
