.TH "/home/brennan/SDP/sdp_ss20_collision_monitoring_for_robotic_manipulators/src/kinova_interfacer.cpp" 3 "Wed Jun 24 2020" "Collision monitoring for robotic manipulators" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/brennan/SDP/sdp_ss20_collision_monitoring_for_robotic_manipulators/src/kinova_interfacer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'ros/ros\&.h'\fP
.br
\fC#include 'visualization_msgs/Marker\&.h'\fP
.br
\fC#include 'geometry_msgs/Point\&.h'\fP
.br
\fC#include 'Eigen/Geometry'\fP
.br
\fC#include 'Eigen/Dense'\fP
.br
\fC#include 'marker_publisher\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 13 of file kinova_interfacer\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Collision monitoring for robotic manipulators from the source code\&.
