.TH "/home/brennan/SDP/sdp_ss20_collision_monitoring_for_robotic_manipulators/include/kinova_arm.h" 3 "Wed Jun 24 2020" "Collision monitoring for robotic manipulators" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/brennan/SDP/sdp_ss20_collision_monitoring_for_robotic_manipulators/include/kinova_arm.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Eigen/Core>\fP
.br
\fC#include <Eigen/Geometry>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <kdl/tree\&.hpp>\fP
.br
\fC#include <kdl/chain\&.hpp>\fP
.br
\fC#include <kdl/chainfksolver\&.hpp>\fP
.br
\fC#include <kdl/chainfksolverpos_recursive\&.hpp>\fP
.br
\fC#include <kdl_parser/kdl_parser\&.hpp>\fP
.br
\fC#include <kdl/frames\&.hpp>\fP
.br
\fC#include <kdl/frames_io\&.hpp>\fP
.br
\fC#include <kdl/chainiksolvervel_wdls\&.hpp>\fP
.br
\fC#include 'primitives\&.h'\fP
.br
\fC#include 'arm\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKinovaArm\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Collision monitoring for robotic manipulators from the source code\&.
